// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseStats struct {
	Total     int `json:"total"`
	Hp        int `json:"hp"`
	Attack    int `json:"attack"`
	Defence   int `json:"defence"`
	SpAttack  int `json:"spAttack"`
	SpDefence int `json:"spDefence"`
	Speed     int `json:"speed"`
}

type Pokemon struct {
	ID        string     `json:"id"`
	PokeID    int        `json:"pokeId"`
	Name      string     `json:"name"`
	BaseStats *BaseStats `json:"baseStats,omitempty"`
}
